# Prometheus configuration for Bingo platform
global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'bingo-monitor'
    environment: '${NODE_ENV}'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # API service metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: /metrics
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api'

  # Realtime service metrics
  - job_name: 'realtime'
    static_configs:
      - targets: ['realtime:4000']
    metrics_path: /metrics
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'realtime'

  # Redis exporter (if using)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    params:
      target: ['redis://redis:6379']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # PostgreSQL exporter (if using)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres'

  # Caddy metrics
  - job_name: 'caddy'
    static_configs:
      - targets: ['web:2019']
    metrics_path: /metrics
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'caddy'

  # Node exporter for host metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'host'